import { ProductCardProps } from "@/interface/index";

export const PRODUCTS: ProductCardProps[] = [
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "Perfume",
    },
    {
        id: "1",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "paris",
        category: "Ouds",
    },
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "RoseLuxury",
        category: "Designer Perfume",
    },
    {
        id: "1",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "Luxury Perfume",
    },
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "Ouds",
    },
    {
        id: "1",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "RoseLuxury",
        category: "women Perfume",
    },
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume3.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "Paris",
        category: "men Perfume",
    },
    {
        id: "1",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume4.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "oil Perfume",
    },
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume5.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "spray french",
    },
    {
        id: "1",
        name: "Designer Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume6.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: [ "popular"],
        brand: "FloralEssence",
        category: "spray Arabic",
    },
]