import { ProductCardProps } from "@/interface/index";

export const PRODUCTS: ProductCardProps[] = [
    {
        id: "1",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "popular",
        brand: "FloralEssence",
        category: "Perfume",
        quantity: 5,
    },
    {
        id: "2",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "New",
        brand: "paris",
        category: "Ouds",
        quantity: 30,
    },
    {
        id: "3",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "Limited Edition",
        brand: "RoseLuxury",
        category: "Designer Perfume",
        quantity: 0,
    },
    {
        id: "4",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume0.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "Bestseller",
        brand: "FloralEssence",
        category: "Luxury Perfume",
        quantity: 2,
    },
    {
        id: "5",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume1.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "Trending",
        brand: "FloralEssence",
        category: "Ouds",
        quantity: 3,
    },
    {
        id: "6",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume2.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "popular",
        brand: "RoseLuxury",
        category: "Luxury Perfume",
        quantity: 50,
    },
    {
        id: "7",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume3.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "New Arrival",
        brand: "Paris",
        category: "men Perfume",
        quantity: 0,
    },
    {
        id: "8",
        name: "Luxury Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume4.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "Luxury",
        brand: "FloralEssence",
        category: "oil Perfume",
        quantity: 15,
    },
    {
        id: "9",
        name: "Elegant Rose Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume5.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "popular",
        brand: "FloralEssence",
        category: "spray french",
        quantity: 25,
    },
    {
        id: "10",
        name: "Designer Perfume",
        description: "A luxurious rose-scented perfume for special occasions.",
        price: 79.99,
        imageUrl: "/assets/image/products/perfume6.jpg",
        rating: 4.5,
        isAvailable: true,
        salePrice: 69.99,
        tags: "popular",
        brand: "FloralEssence",
        category: "spray Arabic",
        quantity: 40,
    },
]